### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#1]

**Comment by vivesing** [comment]
1. Header for mobile layout
![image](https://github.com/aemsites/icicidirect/assets/38683124/67496616-9539-4b29-9b9d-39eec5231ac9)
2. Hamburger menu for mobile layout
![image](https://github.com/aemsites/icicidirect/assets/38683124/44799084-fa1a-4ffe-8102-2edef9dc3cb5)
3. Header for desktop layout
![image](https://github.com/aemsites/icicidirect/assets/38683124/713d2d4d-591d-4336-88ae-c7163cb9bd6e)
Working on these regions of the page for both desktop and mobile experience.
