### ISSUE TITLE
CTA block

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#108]
![image](https://github.com/aemsites/icicidirect/assets/1191451/cc2faae2-4ed3-4317-9c94-cd03969ed1e2)

Requirements:
1. Should have a carousel effect.
2. Ability to specify more that 1 image.
3. CTA form on the right side

[More details](https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/Shared%20Documents/sites/icicidirect/internal/AEM%20-%20Business%20Team%20Requirement_final.xlsx?d=w9f5f55c7a7b6492684c6128abc11816d&csf=1&web=1&e=IoQkfK)

**Comment by anagarwa** [comment]
Open question -
1. Do we have more MockUps
2. Banner is coming from APIs. 
3 What all values should Form have
