### ISSUE TITLE
Remove "padded" section variant

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#111]
Most of the sections already have fixed width and don't need "padding" section style to be specified by authors. This task is to remove this style.

**Comment by shrotia** [comment]
I have updated the page here, please have a look and confirm. I will replicate the changes to original Word document.

Page: https://main--icicidirect--aemsites.hlx.live/draft/shroti/equity
Document: https://main--icicidirect--aemsites.hlx.live/draft/shroti/equity?view-doc-source=true

**Comment by JiangLong2019** [comment]
Looks good

**Comment by shrotia** [comment]
I have updated the main word document: https://main--icicidirect--aemsites.hlx.live/research/equity
