### ISSUE TITLE
Scroll experience in mob view

### ISSUE THREAD

**Issue by ravverma** [aemsites/icicidirect#161]
scroll experience need to be implemented.

**Comment by anagarwa** [comment]
@ravverma  add  the videos for better understanding of the issue

**Comment by ravverma** [comment]
Uploading Screen Recording 2024-04-15 at 6.51.25 AM.mov…

**Comment by ravverma** [comment]
https://github.com/aemsites/icicidirect/assets/46780200/e934ee20-1a7d-48b6-ae03-f898944dc8cf
