### ISSUE TITLE
Incorrect quick link is getting highlighted when particular section is loaded using deep linked url

### ISSUE THREAD

**Issue by yugandhar02** [aemsites/icicidirect#173]
1. As seen in screenshot below, incorrect link is getting highlighted.
![image](https://github.com/aemsites/icicidirect/assets/11800332/f7fcd796-f7e9-4ab9-9a10-5d6e7378648c)

2. When quick link is clicked, url in address bar is not modified.

**Comment by anagarwa** [comment]
@yugandhar02  that is not happening in the original website as well ?

**Comment by anagarwa** [comment]
@vivesing  do we support this ?

**Comment by vivesing** [comment]
> As seen in screenshot below, incorrect link is getting highlighted. 

Thanks @yugandhar02 for finding this, I can relook into this 

> When quick link is clicked, url in address bar is not modified.

This beahviour has been added intentionally to match the original page
