### ISSUE TITLE
Quicklink is sliding to wrong position

### ISSUE THREAD

**Issue by anagarwa** [aemsites/icicidirect#177]
https://github.com/aemsites/icicidirect/assets/19485818/571b7c2d-c049-455e-847f-2b8c7167e202

**Comment by anagarwa** [comment]
cc: @vivesing

**Comment by vivesing** [comment]
Hi @anagarwa , I see it is taking the user to the ilens and blogs section, can u close the sidekick and try again, what is the bug here?

**Comment by anagarwa** [comment]
@vivesing I can still see it.
