### ISSUE TITLE
Review to Implement Tab Block into two Different Media and IPO Block

### ISSUE THREAD

**Issue by anagarwa** [aemsites/icicidirect#180]

**Comment by ravverma** [comment]
@sdmcraft @anagarwa 
as Per my understanding we want this kind authoring like, Media and IPO block could be used standalone and if author want them in tab then use Tabs block. If this is align then I will start working on same direction.
<img width="499" alt="image" src="https://github.com/aemsites/icicidirect/assets/46780200/cb2dcfe0-82e0-419d-ab20-0a99353f5174">

**Comment by ravverma** [comment]
After the current clarification in IPOs api that Only one api is there then we don't need IPO in the tab view at all, SO the IPO could be standalone block now. 
for the media(video/podcast) , I can chop out video and podcasts as standalone media block ( already done locally ) as well and the tabs(media) variant as well.
@sdmcraft
