### ISSUE TITLE
Align FinACE with Upcoming/Recent IPO

### ISSUE THREAD

**Issue by JiangLong2019** [aemsites/icicidirect#197]
<img width="1335" alt="image" src="https://github.com/aemsites/icicidirect/assets/57093988/e1c8e211-50c4-4e9b-a8fe-c6e068853c03">

**Comment by ravverma** [comment]
@JiangLong2019 It is already done under https://github.com/aemsites/icicidirect/commit/315d66dedf3d6335095419a68efb04736d6074a0
