### ISSUE TITLE
Define a way to in Documents which specify that a config is fixed and should not be altered from the customer

### ISSUE THREAD

**Issue by anagarwa** [aemsites/icicidirect#202]
Scope of this task
1. In Each of the Block define which configs are fixed. 
2. Propose a standard way to showcase these immutable configs in block table.

**Comment by ravverma** [comment]
lets define the `fixed` first.
candidates are:

- `Keys` name which can't be changed , like `type` , `title`, `link`, `visible card` etc.
- `Values` : which can be came from a set of defined values , ex: api name like `videos`, `podcasts`, `finance`, `Intraday`, `All` 
- `Values` : which could be any string or number.

Now one more thing is which `keys` are mandatory to provide like if I doesn't provided the `title` and my block still render (designed that way) then Providing `title`   key:value pair is not mandatory but providing `Dropdowns` in `Multi Panel Carousel` is mandatory.

So we can take color code to define these constraints 
`Keys` : RED  
`Values` ( from a defined set) : BLUE
`Values` (any) : BLACK
`Keys (mandatory to provide) `: RED* ( could be a different color but asterisk gives the uniformity with a general form design and asterisk could be handled in code)

ex:
<img width="645" alt="image" src="https://github.com/aemsites/icicidirect/assets/46780200/be29562a-6620-4bcf-bf44-181556b2999e">

**Comment by anagarwa** [comment]
@ravverma  IMO we should close this, since we are updating just the blocks now ?

**Comment by anagarwa** [comment]
We will update this information in BLock Library only. Closing this issue,
