### ISSUE TITLE
FinACE breaks in mobile device?

### ISSUE THREAD

**Issue by JiangLong2019** [aemsites/icicidirect#204]
I found this when I checked other PRs, seems the FinACE breaks in iPhone.

https://main--icicidirect--aemsites.hlx.live/research/equity

![image](https://github.com/aemsites/icicidirect/assets/57093988/2d039b71-e0dd-4def-b308-511cb1ec777e)

**Comment by ravverma** [comment]
> I found this when I checked other PRs, seems the FinACE breaks in iPhone.
> 
> https://main--icicidirect--aemsites.hlx.live/research/equity
> 
> ![image](https://private-user-images.githubusercontent.com/57093988/325458728-2d039b71-e0dd-4def-b308-511cb1ec777e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTQwNzAsIm5iZiI6MTcxNDM1Mzc3MCwicGF0aCI6Ii81NzA5Mzk4OC8zMjU0NTg3MjgtMmQwMzliNzEtZTBkZC00ZGVmLWIzMDgtNTExY2IxZWM3NzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAxMjI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNzNhMGI4MDQzZDgwYjJmNjg4YzZkMzMyY2I0MmNiZTJiMzM1ZDIwYzdiYzNkMTA3OTllYzNlMjlhYzZjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O--A8F6eLw6hy-JDOSW8ZTpzyqHf5RILNLF1WvcVJQI)

seems ok to me..
<img width="824" alt="image" src="https://github.com/aemsites/icicidirect/assets/46780200/c19153c4-c812-4b21-8d9f-26385bd05a4b">

**Comment by anagarwa** [comment]
can we close this @JiangLong2019 @ravverma  ?

**Comment by JiangLong2019** [comment]
@ravverma I still can reproduce it but this time is recent-report.
![image](https://github.com/aemsites/icicidirect/assets/57093988/81948599-05d4-4465-9414-961da7896947)

**Comment by anagarwa** [comment]
@JiangLong2019  @ravverma For me , recent report is not visible on mobile.
![image](https://github.com/aemsites/icicidirect/assets/19485818/78286237-f18a-4a17-b8d0-9836472aca5e)

**Comment by anagarwa** [comment]
@ravverma @JiangLong2019 should we close this issue ?

**Comment by JiangLong2019** [comment]
@anagarwa Now the api doesn't return any data, I will check when it works.

**Comment by ravverma** [comment]
I have checked on my mobile both FinACE and recent report are working fine, even I am not seeing the overflow which @JiangLong2019 was showing during daily

**Comment by JiangLong2019** [comment]
Thanks @ravverma, following is my device information. 
OS: iPhone13 15.6.1
Browser: Safari

Let me get one more answer, if it's not reproducible, I'll close it.
@sdmcraft @anagarwa @vivesing @sneharora1 Are you able to reproduce this ticket?

**Comment by vivesing** [comment]
FinAce block is working fine on both iphone chrome and safari for me.

**Comment by JiangLong2019** [comment]
Thanks @vivesing, how about recent-report?

**Comment by vivesing** [comment]
Recent Reports block also works fine on iphone chrome and safari browsers

**Comment by JiangLong2019** [comment]
Thanks @vivesing, close it.
