### ISSUE TITLE
Upcoming IPO block should be dynamically pop out from side-by-side layout on the basis of number of IPOs

### ISSUE THREAD

**Issue by ravverma** [aemsites/icicidirect#212]
Requirement discussed with customer.

Default : Both block should show side-by-side when only one IPO , at the moment if IPOs > 1 , automatically Upcoming IPO block should be removed from side-by-side view and start shown as standalone.

Author's control :- Author can place upcoming IPO block either in side-by-side view or standalone forcefully regardless number IPOs.
at a time only one of these would be applicable.

<img width="485" alt="image" src="https://github.com/aemsites/icicidirect/assets/46780200/6a0c2eec-094c-4db6-9fe1-994df7bf711f">

**Comment by anagarwa** [comment]
@ravverma  IMO this is not UAT Blocking, we can move this to Good to have milestone ?

**Comment by ravverma** [comment]
> @ravverma IMO this is not UAT Blocking, we can move this to Good to have milestone ?

agreed , changing milestone

**Comment by anagarwa** [comment]
@ravverma AFAIK,  we are keeping this one in feature branch only not merging in the main . 
If that is the case, may be can close this issue with mentioning of the relevant details ?

**Comment by ravverma** [comment]
> @ravverma AFAIK, we are keeping this one in feature branch only not merging in the main . If that is the case, may be can close this issue with mentioning of the relevant details ?

yes, feature is stashed under branch `popup-feature`.
closing issue.
