### ISSUE TITLE
Implementing Nifty and Sensex Auto Refresh Sections

### ISSUE THREAD

**Issue by anagarwa** [aemsites/icicidirect#22]
Scope of The task - 
Currently NIfty and Sensex Indexes are displayed on https://www.icicidirect.com/research/equity page which are being updated without manual refresh. Same needs to be implemented in EDS as well

<img width="531" alt="image" src="https://github.com/aemsites/icicidirect/assets/19485818/fd7ba185-ad1f-43fc-9049-72c036e32db6">

**Comment by vivesing** [comment]
No @ravverma, the UI integration with the mock API is remaining write now the data is static

**Comment by anagarwa** [comment]
@ravverma assigning this to you
