### ISSUE TITLE
[BugBash]Dropdown should be hidden in case of No Response from API

### ISSUE THREAD

**Issue by anagarwa** [aemsites/icicidirect#242]
<img width="1316" alt="image" src="https://github.com/aemsites/icicidirect/assets/19485818/8910252d-da0e-49b2-8361-51c2c34b4030">
Investing Ideas dropdowns are driven from APIs. Since APIs are not responding. DropDown should be hidden in that.

**Comment by vivesing** [comment]
Since its an edge case where API is not returning response, we decided to keep it as it is for now, @anagarwa please see if than can be closed

**Comment by anagarwa** [comment]
@vivesing PR already in place with another improvement in dropdown https://github.com/aemsites/icicidirect/pull/255/files#diff-df1b2d463c6833ad8072b28c5a30afb20ba6675ffa4fad33cc4a1e287b7cfe1fR564
