### ISSUE TITLE
[BugBash] Top hero doesn't switch images when the dot moves in mobile device

### ISSUE THREAD

**Issue by JiangLong2019** [aemsites/icicidirect#246]
![image](https://github.com/aemsites/icicidirect/assets/57093988/8a8bf50a-51c7-425f-afd0-f6849db9be7a)
OS: iPhone
Browser: Safari

**Comment by JiangLong2019** [comment]
Hi @vivesing, I think this issue has been fixed by https://github.com/aemsites/icicidirect/pull/247. Seems I still can reproduce it on iPhone, how about it in your end?

**Comment by vivesing** [comment]
Hi @JiangLong2019, on iphone chrome its switching images correctly, although tapping on the dots is not that easy bit
its working fine on safari as well.

**Comment by JiangLong2019** [comment]
Thanks @vivesing, seems it only happens to me, let me close this thicket.
