### ISSUE TITLE
Document secure API invocation architecture

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#25]
Logging this ticket to document the architecture for invoking secure APIs.
Related to #16

**Comment by anagarwa** [comment]
To the Secure APIs from Frond End we have implemented an Edge Worker which resides in CF.
Below is the basic architecture for the same.
<img width="1661" alt="image" src="https://github.com/aemsites/icicidirect/assets/19485818/dade2a97-5795-42d7-8c44-464121c99e36">
Worker code is present at https://github.com/aemsites/icicidirect/blob/main/tools/api-proxy/secureapi-proxy.js
