### ISSUE TITLE
Document approach for auto-refresh content on page

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#26]
...for items such as Nifty/Sensex index which automatically refresh.

**Comment by anagarwa** [comment]
This can be done via maintaining a websocket server as as edge worker and creating a connection to websocket and fetching information using that web socket.
Sample example implementation https://websocketest--icicidirect--aemsites.hlx.page/draft/anagarwa/websockettesting/
where timestamp is fetched from websocket server and displayed on UI.

NIFTY and Sensex Auto Content Refresh #22 can be implemented using this appraoch.

**Comment by sdmcraft** [comment]
This has been completed.
