### ISSUE TITLE
Confirm the behaviour of Date and Nifty and Sensex Indexes 

### ISSUE THREAD

**Issue by anagarwa** [aemsites/icicidirect#295]

**Comment by anagarwa** [comment]
Issue was raised in the pr https://github.com/aemsites/icicidirect/pull/294#issuecomment-2188357829.
Please confirm and update if any change is require for the same.

**Comment by anagarwa** [comment]
One thing which I have noticed is that one market is open we intentionally hide the date.
as confirmed from the behaviour here .
https://github.com/aemsites/icicidirect/blob/main/scripts/blocks-utils.js#L604
and 
https://github.com/aemsites/icicidirect/blob/main/blocks/header/header.css#L847
cc: @ravverma @sdmcraft

**Comment by anagarwa** [comment]
The same behaviour is observed in their live website as well.

https://github.com/aemsites/icicidirect/assets/19485818/78420f1d-b38f-419b-b35e-03c6d487f2b1

@ravverma  please confirm if its ok to close now.

**Comment by ravverma** [comment]
> The same behaviour is observed in their live website as well.
> 
>  NiftySensexAutoUpdate.mov 
> @ravverma please confirm if its ok to close now.

I think we are ok then.
