### ISSUE TITLE
Trending News Card

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#4]
<img width="1395" alt="image" src="https://github.com/aemsites/icicidirect/assets/1191451/277fda95-195b-421e-ae68-b46a6b6b8741">
Dynamic block based on API response. Must be an adaptation of the vanilla cards block.

**Comment by anagarwa** [comment]
<img width="1397" alt="image" src="https://github.com/aemsites/icicidirect/assets/19485818/d1cd08b2-8e7a-4a41-984f-5f86af7ec0a4">
