### ISSUE TITLE
Finace block

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#57]
<img width="772" alt="image" src="https://github.com/aemsites/icicidirect/assets/1191451/3434429b-9f52-40fb-8628-7b592591b923">

A dynamic block to pull data from api and show up cards in a carousel. The individual items in the carousel are cards.

**Comment by anagarwa** [comment]
@shrotia  have you started on this one ?

**Comment by shrotia** [comment]
> @shrotia have you started on this one ?

I tried using the existing Carousel, but it seems it's very specific for 'oneclickportfolio', 'trading', and 'investing'. I'm figuring out how to make it generic for other Carousels we have on the page.

**Comment by anagarwa** [comment]
@shrotia if it comes too much effort to make it generic, we can look at making a different variant of carousel since there are multiple carousel (like videos and podcast)and making a generic carousel might become too tricky.

**Comment by shrotia** [comment]
Because all the carousels look the same, I believe we should have just one carousel for various experiences. 

> we can look at making a different variant of carousel since
I'm working on one that will consume this: https://main--aem-block-collection--adobe.hlx.live/block-collection/carousel
