### ISSUE TITLE
Authoring walk-through session for customer site authors

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#72]
This task is logged to do a authoring walk-through session for customer site authors. The idea is to enable them to be able to carry out site authoring activities on the Edge Delivery site independently. The session must be recorded.

**Comment by anagarwa** [comment]
We have completed the first session with the customer. 
Keeping this open for more session basis of requirement.

**Comment by vivesing** [comment]
Document in Progress:
Tutorial 1: QuickStart Guide For Developers - https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/icicidirect/docs/Tutorial%201%20Quick%20Start%20Guide.docx

**Comment by sdmcraft** [comment]
Closing this as authoring deep dive session was done with ICICI Sec team in May last week.
