### ISSUE TITLE
Add assets integration

### ISSUE THREAD

**Issue by sdmcraft** [aemsites/icicidirect#84]
Refer https://www.aem.live/docs/aem-assets-sidekick-plugin
This is to be added on an experimental basis if ICICI have a use case for this. If not we can roll it back.

**Comment by yugandhar02** [comment]
<img width="1296" alt="image" src="https://github.com/aemsites/icicidirect/assets/11800332/712d89e4-3a0b-44a8-a624-f1a1313097ca">
AEM Assets selector is visible in sidekick now
